using DZzzz.Learning.Core.Filters.Filters;
using Microsoft.AspNetCore.Mvc;

namespace DZzzz.Learning.Core.Filters.Controllers.Test3
{
    [ProfileFilter]
    // NOTE: this code doesn`t work in Firefox!!!!
    // Writing htMl fragments directly to the response relies on the browser being tolerant of badly formed
    // htMl documents: the div element that i generate in the filter appears at the start of the response body, before
    // the DOCTYPE and html elements that indicate the start of the htMl document generated by the razor view.this
    // technique works and can be useful for producing diagnostic information, but it isn’t something you should rely
    // on for production features
    public class Test3Controller : Controller
    {
        public ViewResult Index() => View("Message",
            "This is the Index action on the Home controller");

        public ViewResult SecondAction() => View("Message",
            "This is the SecondAction action on the Home controller");
    }
}